config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  resources :sessions
  resources :users

  resources :clients do
    member do
      get :credits, :deposits, :bills,
      :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
      :archive_deposits, :archive_credits, :archive_bills,
      :new_bill, :new_credit, :new_deposit
    end
  end


  resources :client_deposits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_credits do
    member do
      get :to_archive
      get :new_transaction
    end
  end


  resources :deposits do
    member do
      get :to_archive
    end
  end
  resources :credits do
    member do
      get :to_archive
    end
  end
  resources :client_bills do
    member do
      get :to_archive
      get :new_transaction
    end
  end


  resources :deposit_operations
  resources :credit_operations
  resources :bill_operations

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/search' => 'clients#index'
  get '/contacts' => 'sessions#contacts'
  get '/trigger' => 'sessions#trigger'
  get '/debtors' => 'client_credits#debtors'


  end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :currency
  has_many :client_deposits
  
  validates :name,  presence: true, uniqueness: true, length: { maximum: 50 }

  validates :term, numericality: { only_integer: true }

  VALID_RATE_REGEX = /\A(([1-9]{1}|[1-9]{1}[0-9]{1}|0).[0-9]{1,2}|100,00)\z/ # 0,12 9,12, 16,00, 100,00 (%)
  validates :rate, presence: true,
  format: { with: VALID_RATE_REGEX }

  validates :widthdrawal, inclusion: { in: [true, false] }

  validates :refill, inclusion: { in: [true, false] }

  validate :check_currency

  private
  def check_currency
    errors.add(:currency_id, "can't find currency") unless Currency.exists?(self.currency_id)
  end

end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :signed_as_manager, except: [:index, :show]

  def index
    @deposit = Deposit.where(:status => true)
  end

  def show
    @deposit = Deposit.find(params[:id])
  end

  def new
    @deposit = Deposit.new
  end

  def create
    @deposit = Deposit.new(deposit_params)
    @deposit.status = true
    if @deposit.save
      flash[:success] = "Successfully added!"
      redirect_to '/deposits'
    else
      render 'new'
    end
  end

  def edit
    @deposit = Deposit.find(params[:id])
  end
  def update
    @deposit = Deposit.find(params[:id])
    if @deposit.update(deposit_params)
      flash[:success] = "Successfully updated!"
      redirect_to '/deposits'
    else
      render 'edit'
    end
  end

  def to_archive
    @deposit = Deposit.find(params[:id])
    @deposit.update(status: false)
    flash[:success] = "Added to archive"
    redirect_to "/deposits"
  end

  def destroy
    @deposit = Deposit.find(params[:id])
    @deposit.destroy
    flash[:success] = "Successfully deleted!"
    redirect_to '/deposits'
  end

  private
    def deposit_params
      params.require(:deposit).permit(:name, :currency_id, :term, :rate, :widthdrawal, :refill)
    end

end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_form.html.erb
<%= form_for @deposit do |f| %>
  <% if @deposit.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@deposit.errors.count, "error") %> prohibited
       this client from being saved:
     </h2>
     <ul>
       <% @deposit.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

<div>
   <div></div>

   <div>
       <div class="label">Name:</div>
       <div class="field">
           <%= f.text_field :name, placeholder: "Name" %>
       </div>
   </div>

   <% currency = Currency.all %>
   <% if !currency.empty?%>
   <div>
       <div class="label">Currency:</div>
       <div class="field">
     <%= f.select(:currency_id) do %>
       <% currency.each do |c| -%>
         <%= content_tag(:option, c[:name] + " " + c[:symbol], value: c[:id]) %>
       <% end %>
     <% end %>
       </div>
   </div>
   <% else %>
       <div>
           <div class="label">Currency:</div>
           <div class="field">
         <select class='spisok'>
             <option value='nil'></option>
         </select>
           </div>
       </div>
   <% end %>

   <div>
       <div class="label">Term:</div>
       <div class="field">
           <%= f.text_field :term, placeholder: "Term" %>
       </div>
   </div>

   <div>
       <div class="label">Rate:</div>
       <div class="field">
           <%= f.text_field :rate, placeholder: "Rate" %>
       </div>
   </div>

   <div>
       <div class="label">Widthdrawal:</div>
       <div class="field">
     <%= f.select(:widthdrawal) do %>
       <% [['Yes', true], ['No', false]].each do |c| -%>
         <%= content_tag(:option, c.first, value: c.last) %>
       <% end %>
     <% end %>
       </div>
   </div>

   <div>
       <div class="label">Refill:</div>
       <div class="field">
     <%= f.select(:refill) do %>
       <% [['Yes', true], ['No', false]].each do |c| -%>
         <%= content_tag(:option, c.first, value: c.last) %>
       <% end %>
     <% end %>
       </div>
   </div>

   <input type='submit', value='Submit', class='button submit green'>

<% end %>

app/views/deposits/edit.html.erb
<title>Edit Deposit</title>
<div class="grey-wrap">
<div class="middle-form">
<h1 class="h1-basic">Edit deposit</h1>
<%= render 'form' %>
<p>
  <%= link_to 'Back', deposits_path, class:"button back orange" %>
</p>

app/views/deposits/index.html.erb
<title>Deposits</title>
<div class="white-wrap">
  <div class="middle-offers">
  <h1 class="h1-basic">Deposits</h1>
  <table>
    <tr>
      <th>Deposit ID</th>
      <th>Deposit Name</th>
      <th>Currency</th>
      <th>Term</th>
      <th>Rate</th>
      <th>Widthdrawal</th>
      <th>Refill</th>
    </tr>
  <% @deposit.each do |deposit| %>
    <tr>
      <td><%= deposit.id %></td>
      <td><%= deposit.name %></td>
      <td><%= Currency.find(deposit.currency_id).name %> <%= Currency.find(deposit.currency_id).symbol %></td>
      <td><%= deposit.term %></td>
      <td><%= deposit.rate %>%</td>
      <td><%= deposit.widthdrawal %></td>
      <td><%= deposit.refill %></td>
      <% if is_manager? %>
        <td>
          <button class="button red" onclick="location.href='/deposits/<%="#{deposit.id}"%>/to_archive'">To archive</button>
          <button class="button orange" onclick="location.href='/deposits/<%="#{deposit.id}"%>/edit'">Edit</button>
        </td>
      <% end %>
    </tr>
    <% end %>
</table>
<% if is_manager? %>
  <button class="button green" style="float: left" onclick="location.href='<%=new_deposit_path%>'">New deposit</button>
<% end %>
</div>
</div>

app/views/deposits/new.html.erb
<title>Add Deposit</title>
<div class="grey-wrap">
<div class="middle-form">
<h1 class="h1-basic">New deposit</h1>
<%= render 'form' %>
<p>
  <%= link_to 'Back', deposits_path, class:"button back orange" %>
</p>