config/routes.rb
Rails.application.routes.draw do

  root 'sessions#index'

  resources :sessions
  resources :users

  resources :clients do
    member do
      get :credits, :deposits, :bills,
      :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
      :archive_deposits, :archive_credits, :archive_bills,
      :new_bill, :new_credit, :new_deposit
    end
  end


  resources :client_deposits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_credits do
    member do
      get :to_archive
      get :new_transaction
    end
  end


  resources :deposits do
    member do
      get :to_archive
    end
  end
  resources :credits do
    member do
      get :to_archive
    end
  end
  resources :client_bills do
    member do
      get :to_archive
      get :new_transaction
    end
  end


  resources :deposit_operations
  resources :credit_operations
  resources :bill_operations

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/search' => 'clients#index'
  get '/contacts' => 'sessions#contacts'
  get '/trigger' => 'sessions#trigger'
  get '/debtors' => 'client_credits#debtors'


  end

app/views/layouts/_client_menu.html.erb
<% if is_manager? %>
<div style="height: calc(100% - 110px)">
  <div class="left-menu">
      <ul>
          <li  class="dropdown">
              <div class="genral-image-h1">
                <i class="fa fa-bars" aria-hidden="true"></i>
                <h1 style="display: inline" class="menu-h1">Profile</h1>
              </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <%= link_to 'Client', "/clients/#{params[:id]}", :class=>"client_menu" %>
                  </li>
                  <li>
                    <i class="fa fa-pencil" aria-hidden="true"></i>
                    <%= link_to 'Edit', "/clients/#{params[:id]}/edit", :class=>"client_menu" %>
                  </li>
                  <li>
                    <i class="fa fa-times" aria-hidden="true"></i>
                    <%= link_to 'Delete', client_path(Client.find(params[:id])),
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' }, :class=>"client_menu" %>
                  </li>
              </ul>
          </li>

          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1">Deposit</h1>
            </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    <%= link_to 'Active', "/clients/#{params[:id]}/deposits" %>
                  </li>
                  <li>
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <%= link_to 'Archive', "/clients/#{params[:id]}/archive_deposits" %>
                  </li>
                  <li>
                    <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                    <%= link_to 'New', "/clients/#{params[:id]}/new_deposit" %>
                  </li>
              </ul>
          </li>


          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1">Credits</h1>
            </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    <%= link_to 'Active', "/clients/#{params[:id]}/credits" %>
                  </li>
                  <li>
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <%= link_to 'Archive', "/clients/#{params[:id]}/archive_credits" %>
                  </li>
                  <li>
                    <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                    <%= link_to 'New', "/clients/#{params[:id]}/new_credit" %>
                  </li>
              </ul>
          </li>



          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1">Bills</h1>
            </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    <%= link_to 'Active', "/clients/#{params[:id]}/bills" %>
                  </li>
                  <li>
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <%= link_to 'Archive', "/clients/#{params[:id]}/archive_bills" %>
                  </li>
                  <li>
                    <i class="fa fa-plus-square-o" aria-hidden="true"></i>
                    <%= link_to 'New', "/clients/#{params[:id]}/new_bill" %>
                  </li>
              </ul>
          </li>

          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1" >Transactions</h1>
            </div>
              <ul class="dropdown-menu">
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'All', "/clients/#{params[:id]}/transactions" %>
                  </li>
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'Credit', "/clients/#{params[:id]}/credit_transactions" %>
                  </li>
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'Deposit', "/clients/#{params[:id]}/deposit_transactions" %>
                  </li>
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'Bill', "/clients/#{params[:id]}/bill_transactions" %>
                  </li>
              </ul>
          </li>
      </ul>
</div>

 <script>
     $(document).ready(function(){
         $('.dropdown .genral-image-h1').click(function() {
             $(this).parent().find('.dropdown-menu').slideToggle("fast");
         });
     });
 </script>
<% else %>
<div style="height: 100%;">
  <div class="left-menu">
      <ul>
          <li  class="dropdown">
              <div class="genral-image-h1">
                <i class="fa fa-bars" aria-hidden="true"></i>
                <h1 style="display: inline" class="menu-h1">Profile</h1>
              </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <%= link_to 'My account', "/clients/#{params[:id]}", :class=>"client_menu" %>
                  </li>
                  <li>
                    <i class="fa fa-cog" aria-hidden="true"></i>
                    <%= link_to 'Change Password', "/users/#{User.find_by_client_id(params[:id]).id}/edit", :class=>"client_menu" %>
                  </li>
              </ul>
          </li>

          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1">Deposit</h1>
            </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    <%= link_to 'Active', "/clients/#{params[:id]}/deposits" %>
                  </li>
                  <li>
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <%= link_to 'Archive', "/clients/#{params[:id]}/archive_deposits" %>
                  </li>
                  <li>
              </ul>
          </li>


          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1">Credits</h1>
            </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    <%= link_to 'Active', "/clients/#{params[:id]}/credits" %>
                  </li>
                  <li>
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <%= link_to 'Archive', "/clients/#{params[:id]}/archive_credits" %>
                  </li>
              </ul>
          </li>



          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1">Bills</h1>
            </div>
              <ul  class="dropdown-menu">
                  <li>
                    <i class="fa fa-credit-card" aria-hidden="true"></i>
                    <%= link_to 'Active', "/clients/#{params[:id]}/bills" %>
                  </li>
                  <li>
                    <i class="fa fa-archive" aria-hidden="true"></i>
                    <%= link_to 'Archive', "/clients/#{params[:id]}/archive_bills" %>
                  </li>
              </ul>
          </li>

          <li  class="dropdown">
            <div class="genral-image-h1">
              <i class="fa fa-bars" aria-hidden="true"></i>
              <h1 style="display: inline" class="menu-h1" >Transactions</h1>
            </div>
              <ul class="dropdown-menu">
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'All', "/clients/#{params[:id]}/transactions" %>
                  </li>
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'Credit', "/clients/#{params[:id]}/credit_transactions" %>
                  </li>
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'Deposit', "/clients/#{params[:id]}/deposit_transactions" %>
                  </li>
                  <li>
                    <i class="fa fa-history" aria-hidden="true"></i>
                    <%= link_to 'Bill', "/clients/#{params[:id]}/bill_transactions" %>
                  </li>
              </ul>
          </li>
      </ul>
</div>

 <script>
     $(document).ready(function(){
         $('.dropdown .genral-image-h1').click(function() {
             $(this).parent().find('.dropdown-menu').slideToggle("fast");
         });
     });
 </script>
<% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>
    <script>
        jQuery(function(){
          jQuery('#camera_wrap_1').camera({
            height: '317px',
            loader: false,
            pagination: false,
            thumbnails: false,
            time:1500, transPeriod:750
          });
        });
      </script>
    <% if !signed_in? %>
    <header>
		<div class="container_12">
			<div class="grid_12">
				<div class="login_div">
					<a href="/" class="logo"></a>
					<nav>
						<ul class="menu">
              <li><a href="/deposits">Deposits</a></li>
              <li><a href='/credits'>Credits</a></li>
							<li><a href="/contacts">Contacts</a></li>
							<li><a href="/signin">Sing in</a> </li>
						</ul>
					</nav>
				</div>
			</div>
		</div>
	</header>
  <% elsif is_manager? && !is_admin? %>
      <header>
      <div class="container_12">
        <div class="grid_12">
          <div class="login_div">
            <a href="/" class="logo"></a>
            <nav>
              <ul class="menu">
                <li><a href="/deposits">Deposits</a></li>
                <li><a href='/credits'>Credits</a></li>
                <li><a href ="/search">Clients</a></li>
                <li><a href=<%= edit_user_path(current_user) %>>My account</a></li>
                <li> <%= link_to "Sign out", signout_path, method: "delete" %> </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </header>
    <% elsif is_admin? %>
        <header>
        <div class="container_12">
          <div class="grid_12">
            <div class="login_div">
              <a href="/" class="logo"></a>
              <nav>
                <ul class="menu">
                  <li><a href="/deposits">Deposits</a></li>
                  <li><a href='/credits'>Credits</a></li>
                  <li><a href ="/search">Clients</a></li>
                  <li><a href="/users">Users</a></li>
                  <li> <%= link_to "Sign out", signout_path, method: "delete" %> </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </header>
    <% else %>
    <header>
    <div class="container_12">
      <div class="grid_12">
        <div class="login_div">
          <a href="/" class="logo"></a>
          <nav>
            <ul class="menu">
              <li><a href="/deposits">Deposits</a></li>
              <li><a href='/credits'>Credits</a></li>
              <li><a href="/contacts">Contacts</a></li>
              <li><a href=<%= client_path(Client.find(current_user.client_id)) %>>My account</a></li>
              <li> <%= link_to "Sign out", signout_path, method: "delete" %> </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>
  <% end %>
  <% if flash[:success] %>
    <div class="message success"><%= flash[:success] %></div>
  <% end %>
  <% if flash[:notice] %>
    <div class="message notice"><%= flash[:notice] %></div>
  <% end %>
  <% if flash[:error] %>
    <div class="message error"><%= flash[:error] %></div>
  <% end %>

    <%= yield %>

    <script>
      setTimeout(function() {
    	$('.success').css({'height': 0, 'padding': 0, 'border': 0});}, 2000);
    </script>
    <script>
      setTimeout(function() {
      $('.notice').css({'height': 0, 'padding': 0, 'border': 0});}, 2000);
    </script>

  </body>
</html>